GET http://localhost:8000/post/



###
GET http://localhost:8000/post/comment/c7293d2c-c954-4374-9676-72ff0543264a/
Content-Type: application/json



### create Comment on a post it take post_id
POST http://localhost:8000/post/comment/c7293d2c-c954-4374-9676-72ff0543264a/
Content-Type: application/json

{
  "text": "new comment from client 4"
}



###  update comment  it take comment_id  
PUT http://localhost:8000/post/comment_id/14/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI5MjEwMjk4LCJpYXQiOjE3MjkxNTYyOTgsImp0aSI6ImU5NDE5Yjk0MGNlYjQ0OTE5NmVjOTBlZjg2ZjRkMzA3IiwidXNlcl9pZCI6IjQzNWZjYzI5LWUwN2YtNDg4Zi1iOTlkLTYxMWY2MGRjZmMwOSJ9.7hgaktvEgsvovdMU5UrinJLHI5HNy6YpG4Vw0kSo2Lc

{
  "text": "updated one"
}

###  Delete comment  it take comment_id  
DELETE  http://localhost:8000/post/comment_id/5/


### like
GET http://localhost:8000/post/like/c7293d2c-c954-4374-9676-72ff0543264a/
Content-Type: application/json


### like or unlike

POST http://localhost:8000/post/like/c7293d2c-c954-4374-9676-72ff0543264a/
Content-Type: application/json




### List Blocked Users
GET http://127.0.0.1:8000/post/block/



### Blocke user
POST http://127.0.0.1:8000/post/block/
Content-Type: application/json

{
  "blocked" : "183eb5e8-bd9a-4cd2-bd3e-52d91ff2f9a0"
}




### unocke user
DELETE  http://127.0.0.1:8000/post/unblock/183eb5e8-bd9a-4cd2-bd3e-52d91ff2f9a0/
Content-Type: application/json




###
GET http://127.0.0.1:8000/api/profile/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI5NjMyMTYyLCJpYXQiOjE3Mjk1NzgxNjIsImp0aSI6IjM4OWEzZWYxMWZmZTQzYTliODQxOWMzOTU5NGExMzVhIiwidXNlcl9pZCI6IjQzNWZjYzI5LWUwN2YtNDg4Zi1iOTlkLTYxMWY2MGRjZmMwOSJ9.rYeKrZ9yvRMrZBN67SY5c15ejHLmK1QWhgNcUCnQ_FU




###
GET http://127.0.0.1:8000/post/saved-posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4NTUxODMzLCJpYXQiOjE3Mjg0OTc4MzMsImp0aSI6ImI2NTNiMDU3NjI1ZTQyZjBhZDZmMWJlOTQxMjJmMmU4IiwidXNlcl9pZCI6IjQzNWZjYzI5LWUwN2YtNDg4Zi1iOTlkLTYxMWY2MGRjZmMwOSJ9.qrK0WMofyj2oOW6LNDBLsA-eRzyZ39aHiSP8CTZ7SpY


###
POST http://127.0.0.1:8000/post/saved-posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI4NTUxODMzLCJpYXQiOjE3Mjg0OTc4MzMsImp0aSI6ImI2NTNiMDU3NjI1ZTQyZjBhZDZmMWJlOTQxMjJmMmU4IiwidXNlcl9pZCI6IjQzNWZjYzI5LWUwN2YtNDg4Zi1iOTlkLTYxMWY2MGRjZmMwOSJ9.qrK0WMofyj2oOW6LNDBLsA-eRzyZ39aHiSP8CTZ7SpY

{
  "post_id":"ce23f51b-ab95-42f2-a985-0c922ad494b2"
}


### getall followers by user id
GET http://127.0.0.1:8000/api/profile/follow/435fcc29-e07f-488f-b99d-611f60dcfc09/?type=followers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI5NjMyMTYyLCJpYXQiOjE3Mjk1NzgxNjIsImp0aSI6IjM4OWEzZWYxMWZmZTQzYTliODQxOWMzOTU5NGExMzVhIiwidXNlcl9pZCI6IjQzNWZjYzI5LWUwN2YtNDg4Zi1iOTlkLTYxMWY2MGRjZmMwOSJ9.rYeKrZ9yvRMrZBN67SY5c15ejHLmK1QWhgNcUCnQ_FU


### get all followings
# http://127.0.0.1:8000/api/profile/follow/user_id/?type=following
GET http://127.0.0.1:8000/api/profile/follow/435fcc29-e07f-488f-b99d-611f60dcfc09/?type=following
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI5NjMyMTYyLCJpYXQiOjE3Mjk1NzgxNjIsImp0aSI6IjM4OWEzZWYxMWZmZTQzYTliODQxOWMzOTU5NGExMzVhIiwidXNlcl9pZCI6IjQzNWZjYzI5LWUwN2YtNDg4Zi1iOTlkLTYxMWY2MGRjZmMwOSJ9.rYeKrZ9yvRMrZBN67SY5c15ejHLmK1QWhgNcUCnQ_FU


### follow a user by passing his user id in payload
POST  http://127.0.0.1:8000/api/profile/follow/435fcc29-e07f-488f-b99d-611f60dcfc09/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI5NjMyMTYyLCJpYXQiOjE3Mjk1NzgxNjIsImp0aSI6IjM4OWEzZWYxMWZmZTQzYTliODQxOWMzOTU5NGExMzVhIiwidXNlcl9pZCI6IjQzNWZjYzI5LWUwN2YtNDg4Zi1iOTlkLTYxMWY2MGRjZmMwOSJ9.rYeKrZ9yvRMrZBN67SY5c15ejHLmK1QWhgNcUCnQ_FU

{
  "user_id" : "055721d7-6ba4-4044-8b9b-640a21f727bd"
}




### unfollow a user  
DELETE   http://127.0.0.1:8000/api/profile/follow/435fcc29-e07f-488f-b99d-611f60dcfc09/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI5NjMyMTYyLCJpYXQiOjE3Mjk1NzgxNjIsImp0aSI6IjM4OWEzZWYxMWZmZTQzYTliODQxOWMzOTU5NGExMzVhIiwidXNlcl9pZCI6IjQzNWZjYzI5LWUwN2YtNDg4Zi1iOTlkLTYxMWY2MGRjZmMwOSJ9.rYeKrZ9yvRMrZBN67SY5c15ejHLmK1QWhgNcUCnQ_FU

{
  "user_id" : "055721d7-6ba4-4044-8b9b-640a21f727bd"
}







### suggestions
GET   http://127.0.0.1:8000/api/profile/suggestion/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI5ODEyNjExLCJpYXQiOjE3Mjk3NTg2MTEsImp0aSI6ImIzOTJjYjliNzEwODQyMzFiYjA1OTQ5OTU5NTE3ZmU4IiwidXNlcl9pZCI6IjQzNWZjYzI5LWUwN2YtNDg4Zi1iOTlkLTYxMWY2MGRjZmMwOSJ9.xPweDQjchnrRjmngMFRYgR5Xi4qfza7yBo2tSE1FaRw



# {
#   "count": 6,
#   "next": "http://127.0.0.1:8000/api/profile/suggestion/?page=2",
#   "previous": null,
#   "results": [
#   ]
# }