# Generated by Django 5.1.1 on 2024-10-06 07:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
