# Generated by Django 5.1.1 on 2024-10-08 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_savedpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedpost',
            old_name='saved_at',
            new_name='created_at',
        ),
    ]
